name: Build daedalOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build and export
        run: |
          npm run build
          npx next export

      - name: Zip exported files
        run: cd out && zip -r ../daedalOS.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: daedalOS
          path: daedalOS.zip